//
// written by Doug Molineux 2/2/2012
// scramble - unscrambles a given word using aspell's word list that can be acquired like this:
// yum install aspell
// aspell dump master > words
// make sure the words file exists in the same directory as this program
// 
// DJM - Modified 3/1/2012
// - Added constants for max sizes of input and file line
// - Made the currentLine and input global for easy function access

#include<stdio.h>
#include<string.h>

#define MAX_LINE_SIZE 80
#define MAX_INPUT_SIZE 40

// declare the currentLine char that will contain the current line
// that the loop pulls out of the string list file
char currentLine[MAX_LINE_SIZE];

// declare the input taken from user, md5 hash is 32 chars, so may need to be
// at least this value
char input[MAX_INPUT_SIZE];

void resetCurrentLine() {

	currentLine[0] = 0;

}

void removeNewline() {

	// removes the new line char at the end of each line, apparently brought in by fgets
        if(currentLine[strlen(currentLine) - 1] == '\n')
        	currentLine[strlen(currentLine) - 1] = 0;
	
}

void getUserInput() {

        // clear the screen
        system("clear");

        // prompt for a word to search
        printf("Enter Word: ");

        // input word
        scanf("%s", &input);

}

int main() {

	// integer used for the counter
	int i = 0; 	

	// integer that can tell if found letters match number of given letters
	int fgLetters;

	// open the words file, that was generated by aspell dump master
	FILE *fp = fopen("words","r");

	getUserInput();

	resetCurrentLine();

	// loop through each line
	while(fgets(currentLine, sizeof(currentLine), fp) != NULL) {

		removeNewline();

		// set the found / given letters to 0
		fgLetters = 0;

		// first make sure that the lengths of the word and of the list word is the same
		if(strlen(currentLine) == strlen(input)) {

			// loop through each letter in the word given
			for(i = 0; i < strlen(input); i++) {

				// search the line for the current letter, if we find it increment fgLetters
				if(strchr(currentLine, input[i]) != NULL)
					fgLetters++;

			}

			// once we have finished looping through the word; evaluate fgLetters
			if(fgLetters == strlen(input)) {

				// fgLetters will be equal to the length of the word if each letter appears in the word
				printf("Match: %s \n", currentLine);

			}

		}

		resetCurrentLine();

	}

	fclose(fp);

	printf("\n\n");

	return 0;

}
