// written by Doug Molineux 2/2/2012
// scramble - unscrambles a given word using aspell's word list that can be acquired like this:
// yum install aspell
// aspell dump master > words
// make sure the words file exists in the same directory as this program

#include<stdio.h>
#include<string.h>

int main() {

	// declare the word that the user will use
	char word[40];
	
	// integer used for the counter
	int i = 0; 	

	// clear the screen
	system("clear");

	// prompt for a word to search
	printf("Enter Word: ");

	// input word
	scanf("%s", &word);

	// set the line that will be read from the file
	char line[80];

	// set the response to the strstr func
	char *resp;
	
	// integer that can tell if found letters match number of given letters
	int fgLetters;

	// open the words file, that was generated by aspell dump master
	FILE *fp = fopen("words","r");

	// loop through each line
	while(fgets(line, sizeof(line), fp) != NULL) {

		// removes the new line char at the end of each line, apparently brought in by fgets
		if(line[strlen(line) - 1] == '\n')
			line[strlen(line) - 1] = 0;
	
		// set the found / given letters to 0
		fgLetters = 0;

		// first make sure that the lengths of the word and of the list word is the same
		if(strlen(line) == strlen(word)) {

			// loop through each letter in the word given
			for(i = 0; i < strlen(word); i++) {

				// search the line for the current letter, if we find it increment fgLetters
				if(strchr(line, word[i]) != NULL)
					fgLetters++;

			}

			// once we have finished looping through the word; evaluate fgLetters
			if(fgLetters == strlen(word)) {

				// fgLetters will be equal to the length of the word if each letter appears in the word
				printf("WE FOUND A MATCH!!! %s \n", line);

			}

		}

	}

	fclose(fp);

	printf("\n\n");

	return 0;

}
