//
// written by Doug Molineux 2/2/2012
// scramble - unscrambles a given word using aspell's word list that can be acquired like this:
// yum install aspell
// aspell dump master > words
// make sure the words file exists in the same directory as this program
//
// DJM - Modified 3/12/2012
// - Added some rudimentary strcat's to increase accuracy of hash decrypt
// - Added makefile to compile source
//
// DJM - Modified 3/2/2012
// - Added support for unscrambling md5 hashes using openssl/md5.h include
// 
// DJM - Modified 3/1/2012
// - Added constants for max sizes of input and file line
// - Made the currentLine and input global for easy function access
//

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "hash.c"

#define MAX_CHAR_SIZE 80
#define VERSION "Scramble 0.4"

// declare the currentLine char that will contain the current line
// that the loop pulls out of the string list file
char currentLine[MAX_CHAR_SIZE];

// declare the input taken from user, md5 hash is 32 chars, so may need to be
// at least this value
char input[MAX_CHAR_SIZE];

// declare mode integer; 1 - no md5, 2 - md5
int mode = 1;

// declare string that contains the hash of each line
char md5Line[MAX_CHAR_SIZE];

void resetVars() {

	// reset the current line (first element to 0) 
	currentLine[0] = 0;

	// reset the value of md5Line (contains the hash of each line as we loop through words)
	memset(md5Line, 0, sizeof(md5Line));

}

void removeNewline() {

	// removes the new line char at the end of each line, apparently brought in by fgets
        if(currentLine[strlen(currentLine) - 1] == '\n')
        	currentLine[strlen(currentLine) - 1] = 0;
	
}

void getUserInput() {

        // clear the screen
        system("clear");

	// print the version and initial instructions
	printf("\n\t%s\n\n \tEnter mode (1 for normal, 2 for MD5):", VERSION);

	// receive mode that the user wants to use
	scanf("%d", &mode);

        // prompt for a word to search
        printf("\n\tEnter Word:");

        // input word
        scanf("%s", &input);

	// print a new line after receiving input,
	printf("\n");

}

int unscrambleWord(int fgLetters) {

	// integer used for the counter
        int i = 0;

	// first make sure that the lengths of the word and of the list word is the same
        if(strlen(currentLine) == strlen(input)) {

        	// loop through each letter in the word given
                for(i = 0; i < strlen(input); i++) {

                	// search the line for the current letter, if we find it increment fgLetters
                        if(strchr(currentLine, input[i]) != NULL)
                        	fgLetters++;

                } // end for

                // once we have finished looping through the word; evaluate fgLetters
                if(fgLetters == strlen(input)) {

                	// fgLetters will be equal to the length of the word if each letter appears in the word
                        printf("\tMatch: %s \n", currentLine);

                } // end if - evaluate length of fgLetters

        }
	
	// return the fgLetters after we have possibly incremented it
	return fgLetters;

}

int main() {

	// used for counter in mode 2
	int i = 0;

	// integer that can tell if found letters match number of given letters
	int fgLetters;

	// char array that will contain integer as string
	char buffer[3];

	// open the words file, that was generated by aspell dump master
	FILE *fp = fopen("words","r");

	// prompt the user to enter a string or md5 hash
	getUserInput();

	// reset all the vars and prepare for loop
	resetVars();

	// loop through each line
	while(fgets(currentLine, sizeof(currentLine), fp) != NULL) {

		// remove the new line that is generated by fgets
		removeNewline();

		// set the found / given letters to 0
		fgLetters = 0;

		// if normal text is entered
		if(mode == 1) {

			fgLetters = unscrambleWord(fgLetters);

		}
		else if(mode == 2) {
			
			// first try to match normal hashed input
			strcpy(md5Line, str2md5(currentLine, strlen(currentLine)));

			// if we find a match then exit 
                        if(strcmp(md5Line, input) == 0) {

				// print the current line
                                printf("\tMatch: %s \n", currentLine);

                        }
			else {
				
				// reset counter
				i = 0;

				// loop through ints 0 - 9
				while(i < 10) {
		
					// convert the counter to a char array
					sprintf(buffer, "%d", i);
					
					// concat the buffer to the current line (add int to string)
					strcat(currentLine, buffer);

		                        // retry matching strings
                		        strcpy(md5Line, str2md5(currentLine, strlen(currentLine)));

 		                        // if we find a match then exit
                		        if(strcmp(md5Line, input) == 0) {

                                		// print the current line
                                		printf("\tMatch: %s \n", currentLine);
						break;

                        		}

					// increment counter
                                        i++;
				
				} // close the while

			} // close the else

		} // close else if (mode check)

		// reset all the variables
		resetVars();

	}

	fclose(fp);

	printf("\n\n");

	return 0;

}
